#????
server:
  port: 8081
  servlet:
    context-path: /bs  #http://localhost:8081/bs/{Controller??class????@RequestMapping?????/Contorller??class????????@RequestMapping?????}
  tomcat:
    uri-encoding: UTF-8

spring:
  profiles:
    active: druid, config
  quartz:
    job-store-type: jdbc #使用数据库存储定时任务
    jdbc:
      initialize-schema: always
    overwrite-existing-jobs: true #每次重启覆盖原有jobs
  redis:
    # ??
    host: localhost
    # ??
    port: 6379
    # ??
    password:
  servlet:
    multipart:
      max-file-size: 2048MB
      max-request-size: 2048MB

minio:
  endpoint: http://120.48.123.209:9000
  accessKey: fileadmin
  secretKey: fileadmin
  bucketName: files

mybatis:
  typeAliasesPackage: com.business.**.po
  mapperLocations: classpath*:mapper/**/*Mapper.xml
  configLocation: classpath:mybatis/mybatis-config.xml