spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    druid:
      #主数据源
      master:
        url: jdbc:mysql://localhost:3306/ruoyi
        username: root
        password: root
      #初始容量大小
      initialSize: 5
      # 最小空闲连接数
      minIdle: 10
      # 最大连接数
      maxActive: 20
      # 最长连接等待时间(单位：ms)
      maxWait: 60000
      # 验证连接是否失效
      validationQuery: SELECT 1 FROM DUAL