#配置服务
server:
  port: 8081
  servlet:
    context-path: /
  tomcat:
    uri-encoding: UTF-8

spring:
  profiles:
    active: druid
  redis:
    # 地址
    host: localhost
    # 端口
    port: 6379
    # 密码
    password:

mybatis:
    typeAliasesPackage: com.business.**.po
    mapperLocations: classpath*:mapper/**/*Mapper.xml
    configLocation: classpath:mybatis/mybatis-config.xml